FROM ubuntu:latest

RUN apt update && apt install -y \
    build-essential \
    cmake \
    git \
    libllvm-dev \
    clang \
    llvm-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY . .

RUN mkdir build && cd build && cmake .. && make

ENTRYPOINT ["./build/matreshka"]